### ISSUE TITLE
다음주 까지 해야할일 (5.21 까지)

### ISSUE THREAD

**Issue by JunsuLime** [HyOsori/Osori-HackDay#12]
Server framework 정하기
Angular 붙여서 해보기

**Comment by JunsuLime** [comment]
Angular Component Tree 구성하기

**Comment by JunsuLime** [comment]
다다음주에 할거 생각하기

**Comment by kimjieun02** [comment]
package dependency 정리하기
* [ngx-socket-io](https://www.npmjs.com/package/ngx-socket-io)

**Comment by kimjieun02** [comment]
venv 설정해오기 :)..

**Comment by JunsuLime** [comment]
Angular 로 짜게 되면 보통 디렉토리 구조가 어떻게 돼?? @kimjieun02

**Comment by kimjieun02** [comment]
가장 바깥에 dependency 관련 config 파일들 있고 같은 위치에 src 폴더가 있어요
src 안에 index.html이랑 모듈, 컴포넌트들이 들어갑니다

**Comment by kimjieun02** [comment]
5월 29일 모임 이후로 할 일
1. angular4+에서 적용되는 websocket 공부하기
: https://tutorialedge.net/typescript/angular/angular-websockets-tutorial/   
2. home page 디자인
3. graph module 개발을 위한 angular module 생성 공부하기
